In [13]:
import torch
import numpy as np
import time
import torch.nn as nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [14]:
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elasped_time = end_time - start_time
print(f"{elasped_time:.8f}")

0.00000000


In [15]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elasped_time = end_time - start_time

print(f"{elasped_time:.8f} seconds")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elasped_time = end_time - start_time

print(f"{elasped_time:.8f} seconds")

0.02600002 seconds
0.11100149 seconds


In [16]:
tensor = torch.tensor([1,2,3,4,5])

out = torch.cat((tensor, torch.tensor([6])), dim = 0)  #dim = 0 for concatening vertically. Will be used for concatening the input and the predicted text
out

tensor([1, 2, 3, 4, 5, 6])

In [17]:
out = torch.tril(torch.ones(5,5)) # we dont know about the future so we keep the next parts of the matrix as zero and then we update it when we get the answers
out #lower triangular matrix

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.triu(torch.ones(5,5))
out #upper triangular matrix

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out = torch.zeros(5,5).masked_fill(torch.triu(torch.ones(5,5)) == 0, float('-inf'))
print(out)
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
print(out)

tensor([[0., 0., 0., 0., 0.],
        [-inf, 0., 0., 0., 0.],
        [-inf, -inf, 0., 0., 0.],
        [-inf, -inf, -inf, 0., 0.],
        [-inf, -inf, -inf, -inf, 0.]])
tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [20]:
print(torch.exp(out))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [21]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape


torch.Size([4, 3, 2])

In [22]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stacking the tensors along a new dimension

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias = False)
print(linear(sample))

tensor([ 7.4678, -3.7419, -8.0084], grad_fn=<SqueezeBackward4>)


In [24]:
import torch.nn.functional as F

tensor = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor, dim = 0)

softmax_output 

tensor([0.0900, 0.2447, 0.6652])

In [25]:
# Initializing embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#
input_indices = torch.LongTensor([1,5,3,2])

#Applying the embedding layer
embedding_output = embedding(input_indices)

print(embedding_output.size())

torch.Size([4, 100])


In [28]:
#matrix multiplication

a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a@b)
#using inbuilt functions

print(torch.matmul(a,b))


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [39]:
int_64 = torch.randint(1,(3,2)).float()

float_32 = torch.rand(2,3)
print(int_64.dtype, float_32.dtype)

result = torch.matmul(int_64, float_32) # 3x2 @ 2x3 = 3x3
print(result)
result1 = torch.matmul(float_32, int_64) # 2x3 @ 3x2 = 2x2
print(result1)


torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
